---
- name:           Ensure kubernetes repo are enabled
  yum_repository:
    name:         Kubernetes
    description:  Google Kubernetes repo
    baseurl:      "https://packages.cloud.google.com/yum/repos/kubernetes-{{ yum_repo }}-x86_64"
    enabled:      true
    gpgcheck:     true
    gpgkey:       "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"

- name:           Ensure kubectl is installed
  yum:
    name:         "kubectl-{{ kubectl_version }}-0.x86_64"
    update_cache: true
    state:        present
